# Generated by Django 5.2.4 on 2025-07-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sale_discount_alter_sale_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('pos', 'P.o.s')], max_length=50),
        ),
    ]
